server:
  port: 8080

spring:
  # config:
  #   import:
  #     - classpath:database.yml        # 引入 database.yml（位于同一模块）
  
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果你的 Redis 服务器设置了密码
      database: 0 # Redis 数据库索引 (默认为 0)

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/talksphere?useUnicode=true
    username: talksphere
    password: Aa123456...
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    map-underscore-to-camel-case: true
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.tt.admin.mapper: DEBUG
# Other configurations can be added as needed.