# # backend/user-service/src/main/resources/database.yml
# spring:
#   datasource:
#     url: jdbc:mysql://127.0.0.1:3306/talksphere?useUnicode=true
#     username: talksphere_user
#     password: Aa123456...
#     driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis-plus:
#   mapper-locations: classpath*:/mapper/*.xml
#   configuration:
#     map-underscore-to-camel-case: true